skillcrush/skillcrush-104

- jamie.rb
> Pull request Jamie

- emily.rb
> edited emily file

- advice/gretchenista-advice.html
- css/gretchenista-advice.css
- index.html
- ruby/gretchenista
- ruby/gretchenista.rb
> gretchenista2.rb

- advice/amandalglittle-advice.html
- css/style.css
- ruby/amanda.rb
Would like to add personal advice page
> Skillcrush 104 forked repo

- ruby/samu.rb
> Samu's file

- nate.rb
- ruby/nate.rb
sorry I forgot to cd into the ruby folder! so there's two and I don't know how to change this /:
> my first forkage 

- advice/jackiechapman-advice.html
- index.html
> Add jackie-chapman-advice.html

- advice/danwalsh-advice.html
- css/danwalsh-style.css
- index.html
- ruby/dan.rb
> I'm committed

- ruby/ryanklement.rb
> added ryanklement.rb to forked repository

- advice/whitney-advice.html
- css/style.css
- ruby/whitney.rb
- whitney-advice.html
- whitney.rb
I moved my files into the correct ruby and advice folders, and closed the old pull request.
> Revised - adding whitney.rb

- ruby/Nataly.rb
Hi, Skillcrush!. This is my first pull request.
> Add hello from Nataly.rb

- advice/robs-advice.html
- css/rob-s-style.css
> Rob S's pull request resubmission

- advice/yami-advice.html
- css/style.css
- index.html
i'm going to do more work on this later to make it even better :)
> added Yami's advice

- advice/seg-advice.html
- css/seg-style.css
- index.html
- ruby/stephenG.rb
> Some commits to my fork

- advice/chrissentman-advice.html
- css/chris-sentman.css
- css/style.css
- index.html
- ruby/chris-sentman.rb
Q) What kind of girl would a Rails guy date? A) A fat model.
> Chris Sentman's got a joke for you

- ruby/christie.rb
> Adding christie file to forked repo

- advice/chrystalfaith-advice.html
- css/style.css
- index.html
- ruby/chrystalfaith.rb
Personalized advice page with link from index page.
> chrystalfaith-advice addition

- advice/camiedecovich-advice.html
- css/style.css
- index.html
- ruby/camie.rb
Added link to index.html to camiedcovich.html.
Added file: advice-camiedecovich.html.
Added camie-advice styles to styles.css.
> Added "Advice from Camie"

- ruby/chrischapman.rb
HI - please merge my code. Thanks!
> test git fork and clone

- advice/adubs-advice.html
- css/adubs-style.css
- index.html
- ruby/al.rb
Requesting both pull challenge and advice pull challenge be added to the Repository!
> Okay! Now, I'm ready to commit!

- advice/melissaae-advice.html
- css/melissaae-style.css
- index.html
- ruby/melissa.rb
Per Lesson 21. Requesting that you pull my changes!
Now added advice page, custom CSS and updated the index.html
> Updated Melissa file

- advice/advice-erussell.html
- css/style.css
- index.html
- liz.rb
- ruby/erussell.rb
> for forking practice

- advice/kristiana-advice.html
- css/kristiana-advice.css
- index.html
- kristiana.rb
> Adding my ruby file after forking. Will now submit pull request.

- advice/jtm-advice.html
- css/jtm-style.css
- index.html
- ruby/a_testAdd.rb
- ruby/a_testAdd2.rb
> JTM_merge01

- advice/advice-erikfortin.html
- css/erik-fortin-styles.css
- ruby/efortin.rb
erik fortin added file for skillcrush-104 class
> erik fortin added file

- advice/albert-advice.html
- albert.rb
- css/style.css
- index.html
Practice for Skillcrush 104 class
> Practicing forking

- advice/shanamoore-advice.html
- css/shanamoore-style.css
- ruby/shana.rb
> Shana test

- advice/shannonwoodward-advice.html
- css/shannonwoodward-advice.css
- index.html
Shannon Woodward's advice for Skillcrush newbies.
> shannon's advice added

- advice/natalya-patrikeeva-advice.html
- css/natalya-patrikeeva-style.css
Added background picture, columns and links.
> Modified HTML and CSS files to be a little more fancy 

- hope.rb
- ruby/hope.rb
skillcruch 104 fork challenge!
> Hope's loop

- advice/holli-advice.html
- css/holli-style.css
- ruby/holli.rb
Things got a little crazy yesterday
> Hoping this is right file

- ruby/katrin.rb
> edited katrin file

- advice/hope-advice.html
- css/hope-advice.css
- index.html
Adding my advice page, my css, and a link to it on the index.
> Hope's advice

- ruby/cooledge.rb
I'm adding my ruby file to the collection of Skillcrush practice pull requests.
> Making my file

- ruby/taiwei.rb
> Added Taiwei file

- advice/tylersherkin-advice.html
- css/tylersherkin-style.css
- index.html
- test.rb
- tyler-sherkin.rb
> Adding tyler-sherkin.rb

- advice/glenda-advice.html
- css/glenda.css
- glenda.rb
- ruby/glenda.rb
Trying hard to catch up. Thanks.
> Advice page, finally!

- ruby/regina.rb
added regina.rb as a file in ruby
> Added regina.rb

- advice/joshstern-advice.html
- css/style.css
- index.html
- ruby/josh.rb
Just added my short Ruby script, and my advice page.
> added a new script

- ruby/a_capella.rb
> w00t look at Amanda's forkin skills!

- advice/advice-acapella.html
- css/style.css
- index.html
whew, the more practice the better!
> Amanda Capella's advice html and css

- advice/segh-advice.html
- css/segh-style.css
- index.html
> Susan's Advice Page

- ruby/alex.rb
Hi. Hope you like the good news in my file! Thanks for helping me learn.
> adding alex file

- advice/alexthenomad-advice.html
- css/alexthenomad-style.css
- index.html
Hi Sharon. I hope I'm doing it right this time.
> adding advice page

- ruby/choyushan.rb
Just another Hello World script
> skillcrush-104

- ruby/melissa-m.rb
Making sure I get the hang of this for class.
> Melissa's addition to Skillcrush 104 repo

- advice/melissam-advice.html
- css/style.css
- index.html
Added my advice page and updated the index.hml & style.css files.
> Melissa's advice page

- advice/advice-Tricia.html
- css/style.css
- index.html
> Tricia's advice

- ruby/marty_cs.rb
Adding marty_cs.rb to skillcrush-104/ruby
> Marty CS added

- ruby/Mimi.rb
I followed the instructions but none of my files were pushing up into the skill crush repo.
> Got tired of trying this through the Terminal.

- advice/amandalilley-advice.html
- amanda.rb
- css/amandalilley.css
- ruby/amandalilley.rb
This is my first forked repository!
> Adding Advice html and css

- advice/harriewilson-advice.html
- css/style.css
- index.html
added advice page, updated style.css and index.html
> skillcrush 104 advice page

- ruby/sandy_hogan.rb
My first forked commit...adding my name to the Skillcrush-104 ruby file.
> Adding my name to ruby file

- advice/jeremiahshafer-advice.html
- css/jeremiahshafer-advice.css
- index.html
- ruby/jeremiah.rb
> New file added

- ruby/rossl.rb
> added file ross.rb

- ruby/emily.rb
The code was corrupted so I replaced with another message
> changed text in Emily.rb

- advice/jenanton-advice.html
- css/jenanton-style.css
- index.html
added link to index file
added advice page
added css stylesheet
> Jenanton's advice

- ruby/colleeniscool.rb
Adding a colleeniscoolfile!  Check it out!
> First commit of the Colleen file

- advice/kumarp34-advice.html
- css/style.css
- index.html
Added an html file with my advice (kumarp34-advice.html)
Updated style.css with my advice styles
Added a link to index.html
> added kumarp34's advice:

- ruby/hjrandolph.rb
Created and adding new file for 104
> Adding hjrandolph file

- advice/advice-template.html
- advice/sandyhogan-advice.html
- css/style.css
- index.html
I have attempted to style up my advice sheet...not exactly how I had hoped for, as I was attempting to make the background color a light blue...and although I added what I thought might work to my styles it remains a white background. Would love any advice as to what I might be doing wrong with that!
> Adding my advice and css files

- ruby/marcus_worth.rb
Hello everyone,
This is my file added to my forked repository.
Cheers
Marcus
> marcus_worth.rb

- advice/danrempel-advice.html
- css/danrempel-style.css
- index.html
- ruby/dan-rempel.rb
> Add file with my name

- advice/chelseal-advice.html
- css/chelseal-advice.css
- index.html
I added my advice to chelseal-advice.html, and updated the index.html file.
> chelsea l's advice

- advice/advice-hjrandolph.html
- css/hjrstyle.css
- index.html
One advice file
One CSS file
One image file
> New Pull Request for HJR's Advice Page

- advice/sarah-gag.html
- css/style.css
- ruby/sarah_g.rb
> sarah_g.rb

- advice/tiffany-advice.html
- css/tiffany-advice.css
- index.html
- ruby/tiffany.rb
> tiffany.rb

- advice/kristyburge-advice.html
- css/kristyburge-style.css
- index.html
Updated index.html file to link to my new advice page and also adding custom css file.
> Added Kristy Burge's advice

- advice/jesselynn-advice.html
- css/jesselynn-style.css
- index.html
First pull request for advice project!
> 104experiments

- advice/psittacine-advice.html
- css/psittacine-advice.css
- index.html
Added my psittacine-advice.html and psittacine-advice.css files, and the link to my page on index.html.
> Added psittacine-advice html & css files, & link on index.

- advice/eevee-advice.html
- css/eevee-advice.css
- index.html
https://github.com/skillcrush/skillcrush-104/commit/f7d5c7f12251b5163a4185438d9f82af14d0002
https://github.com/skillcrush/skillcrush-104/commit/232851810df52fdf7d31e17a9dbe56434214b3b93
> Push request for advice html and css files

- advice/bosstonprowell-advice.html
- css/bosston-style.css
- index.html
I just created my advice page.
> added my advice page

- ruby/dave.rb
> added dave.rb

- advice/maleneallen-advice.html
- css/style.css
- index.html
> Deletion recovered

- advice/maleneallen-advice.html
- css/style.css
- index.html
> malenes advice changes

- advice/parismarron-advice.html
- css/style.css
- index.html
> Paris's advice

- advice/ashleybrown-advice.html
- css/style.css
- index.html
> Added Ashley B's advice

- advice/lp-advice.html
- css/style.css
- index.html
I added my advice section index.html and my styling in the css. Thanks!
> added my advice section in html and styling in css

- advice/megmiller-advice.html
- css/megmiller-style.css
- index.html
Added my "style" to the mix! Thanks for a great experience!
> added megz advice to html, added new css, new advice html

- advice/dawncat-advice.html
- css/style.css
- index.html
- ruby/dawn.rb
Added my named file, only one file changed this time.
> adding dawn file

- advice/kirsten-advice.html
- css/kirsten-style.css
- index.html
Submitting my advice page for Skillcrush class 105. Thanks!
> added kirsten advice html, css, and index link

- advice/advice-from-shannon.html
- css/style.css
- index.html
Added my advice and some styling
> Addition of advice from shannonc

- advice/advice-evelin.html
Changed a line of text in the advice file
> Modified advice file

- ruby/nathan.rb
Hello! Here is my pull request!
Sincerely,
Nathan Rathge
> Commit nathan.rb

- ruby/carson.rb
Added carson.rb to the ruby file for Skillcrush.
> Added my own file.

- advice/jennbee-advice.html
- css/jennbee-style.css
- index.html
> added jennbee advice

- advice/sara-advice.html
- css/style.css
- index.html
Added my own advice page for Skillcrush 105. It's my first pull request. Hopefully I'm doing it right!
> added sara's advice page along with updated link and css

- advice/joel-advice.html
- css/style.css
- index.html
> added joel-advice page, added class to CSS, added link to index.html

- advice/advice-sara-suzanne.html
- css/style.css
- index.html
> added Sara Suzanne Advice page and updated index and css files

- advice/jennimacklin-advice.html
- css/jennimacklin-styles.css
- index.html
Adding my advice for fellow skillcrushers!
> jenni macklin adding advice

- advice/loriwesthaver-advice.html
- css/loriwesthaver-style.css
- index.html
I've added some advice for newbie developers!!
> added my advice

- advice/rookssj-advise.html
- css/rookssj.css
Made changes now trying pull request.
> css changes

- advice/stevehemmer-advice.html
- css/stevehemmer-style.css
- index.html
> modified index.html, added css, addednew html

- advice/ross_advice.html
- css/ross_j.css
- index.html
- rossgitfilenew.rb
- ruby/rossgitfilenew.rb
> first commit

- advice/amandareidy-advice.html
- css/amandareidy.css
- index.html
Included my advice to newbies and updated link to my page in main html. I also amended the last couple of links to include <br> tags correctly : )
> my advice for newbies

- advice/ef-advice-template.html
- css/ef-style.css
- index.html
I hope I updated this correctly. =/
> Fixed my boo boo

- advice/ef-advice-template.html
- css/ef-style.css
- index.html
I've updated:
advice/ef-advice.html
css/ef-style.css for advice/ef-advice.html
added link to index.html to advice/ef-advice.html
> EF Pull Request 7.15.16

- advice/advice-by-lee.html
- advice/leandra-advice.html
- css/leandra.css
I am submitting my very first pull request.
> Pull Request

- advice/medmonson-advice.html
- css/medmonson-style.css
- index.html
adding my advice and style files
> medmonson advice edits and files

- advice/sbw-advice.html
- css/sbw-advice.css
- index.html
Added my Advice, Sol Barrera Watters,  July 2016 WP and FED blueprints
> Added solybarr advice

- advice/elizakocken-advice.html
- css/style.css
- index.html
Hi there! I created my own advice page to add to this site, for the 105 Git course!
Please accept my code.
Eliza
> Eliza's Advice page added

- advice/genevieve-advice.html
- css/style.css
- index.html
> My changes

- advice/caro-l-advice.html
- css/caro-l-style.css
- css/style.css
Added html file ("caro-l-advice.html") to advice folder and changed the title, headlines, and text to personalize.
> changed html text

- advice/marquisbrown-advice.html
- css/style.css
- index.html
https://github.com/skillcrush/skillcrush-104/commit/87fbbd69bf7eff60cba61ec8c15327035a21c85c
Here's my advice file
> Advice file

- advice/sikiolaniran-advice.html
- css/sikiolaniran-advice.css
Changes made to index.html and added new css file.
> Modified advice page for 104

- advice/katemanning-advice.html
- css/katemanning-style.css
- index.html
- ruby/kate-manning.rb
Practice practice practice ...
> Practicing pull and merge

- advice/rebeccawf-advice.html
- css/rebeccawf-advice-style.css
- index.html
A new style.css file was created and placed into the css folder, and a new html file was added to the advice folder to reflect my own advice. Lastly, a link was added to the index.html file. Yay!
> Modifications

- advice/priya-advice.html
- css/priya-style.css
> made my changes

- advice/daria-advice.html
- css/daria-style.css
Hey, I made some changes to your CSS file. Hope you'll like them.
> ../advice/daria-advice.html

- advice/heidilowry-advice.html
- css/style.css
- index.html
Hello! Adding my advice to the file. :) Yay Skillcrush 105!
> Heidi advice

- advice/aurelie-advice.html
- css/aurelie-style.css
- index.html
Hello,
Here is my fork for the challenge in Skillcrush 105.
Thanks a lot!
> changes made on skillcrush-104 to learn a team workflow process

- advice/jeanne-advice.html
- css/style.css
- index.html
I added some advice. Check it out :-)
> adding Jeanne's advice

- advice/amberlovell-advice.html
- css/amberlovell-style.css
- index.html
> adding advice css and index with amber lovell changes

- advice/larrygibbs-advice.html
- index.html
I will go back and do more changes to my page at a later date. Just wanted to get some experience doing pull requests first!
> Experiment

- advice/virginiagivesgreatadvice.html
- css/style.css
- css/virginiarobinson-style.css
- index.html
Adding my advice page to the project!  :)
> adding virginia's advice page

- advice/anela-advice.html
> anela-advice added

- advice/advice-alicia.html
- css/style.css
- index.html
Hi! I did the whole exercise again from scratch. I hope it's working now!!
Sorry for the extra work :)
> committing Alicia's Advice

- advice/advice-kellyvon.html
- css/kellyvon_style.css
- css/style.css
- index.html
> Added Kelly Von styles

- advice/christinaz-advice.html
- css/christinaz-style.css
- index.html
Added my advice page & some `<br>`s between page listings
> added Christina Z's advice page... also fixed some index breaks

- advice/advice-smiles.html
- css/normalize.css
- css/smiles-style.css
- index.html
I've added my advice (both html and css) to the page for Skillcrush 105, and cleaned up some bad break code in the index.html.
> smiles advice added

- advice/maloriesouser-advice.html
- css/maloriesouser-style.css
- index.html
I would like to add my advice page to the skillcrush/skillcrush-104 repo. Thank you for your time.
> created my advice page, css, and added link to index.html

- advice/advice-dianac.html
- css/dianac-advice.css
- index.html
> index styles and stylesheet edited

- advice/advice-lisahuang.html
- css/lisahuang-style.css
- css/style.css
- index.html
Added my advice with dedicated .css and .html files, please merge!
> added Lisa Huang advice CSS and html files

- advice/advice-nadine-rodriguez.html
- css/style.css
My first pull request. Getting the hang of this. Happy Coding =)
> Skillcrush 104

- advice/joannesullivan-advice.html
- css/style.css
- index.html
added Joanne's advice to newbies
> added Joanne's advice

- advice/lorib-advice-template.html
Added a few new tips to content. Css just played a little with colors. Not sure how it would merge with others, do we have just a big master with lots of advice?.
> change content and css for main page advice

- advice/nelita-advice.html
- css/nelita-styles.css
this is Nelita's fist pull request
> Nelita's Advice Changes

- advice/alexchristoffel-advice.html
- index.html
These are my changes to the code for my advice.
> alexchristoffel changes

- advice/advice-caroline.html
- css/style.css
- index.html
> Added Caroline's advice

- advice/teslimni-advice.html
- css/teslimni-advice.css
- index.html
Just added my advice page to the project for integration.
> Added my advice page html, css and link to the index page

- advice/amykotas-advice.html
- index.html
*crossing fingers this worked*
> Wrote my advice page and added it to the group list.

- advice/advice-susannawise.html
- css/style.css
- index.html
Added my own page to the project! Yay!
> Added Susanna Wise's Advice

- advice/tiffanyingle-advice.html
I think I committed this 4 or 5 times, but not on purpose.
> Tiffany Ingle's advice

- advice/cotterpinx-advice.html
- css/style.css
SK 105 git pull lesson -- added custom styles and custom advice file; didn't add a link to the index, as it's pretty lousy advice. ;-)
> added a cotterpinx advice file + styles

- advice/mbrown-advice.html
- css/style.css
- index.html
Advice that I would like to add. :)
> Added advice from mbrown.

- advice/biskitcrumbs-advice.html
- css/style.css
- index.html
A grossly pink page because I am an HTML newb and still a lowly grasshopper : )
> edited and added biskitcrumbs advice

- advice/mariask-advice.html
- css/mariask-style.css
- index.html
Created my advice page and added link to index.html file
> Maria K's Advice

- advice/advice-mmjb.html
- css/advice-style-mmjb.css
Skillcrush-105 Task Assignment Experiment Submission
> Adding html and css files for Melody's Skillcrush-105 Task

- advice/katiehart-advice.html
- css/style.css
- index.html
I added my advice page for the 105 lesson in Front-End Developer. I also aligned a few links above mine that were not properly indented.
> added Katie Hart advice page

- advice/kristinantosz-advice.html
- css/style.css
- index.html
> 104 challenge

- advice/brihayley-advice.html
- css/style.css
- index.html
> created a brihayley advice page and edited the css

- advice/aarondan-advice.html
- css/style.css
- index.html
Created advice page, added styles to style.css and link to index.html
> Added advice from Aaron

- advice/sherriattili-advice.html
- css/style.css
- index.html
I've been holding onto to submitting this pull request, because it just didn't seem right (among other time delays).  Fingers cross this works!
> My advice and first push

- advice/crhudy-advice.html
> created my advice page

- advice/advice-laracorum.html
- index.html
> Lara added advice

- advice/advice-lexi-zgud.html
- css/advice-lexi-zgud.css
- index.html
Some coding advice I want to share!
> Lexi added advice!

- advice/allison-advice.html
- css/allison-advice.css
- ruby/allison.rb
Added the new, shiny allison.rb script!
> Added allison.rb

- advice/gracebell-advice.html
- css/gracebell-style.css
- index.html
Pull request from Skillcrush-105 Git Safari Section.
> added link in index.html, created gracebell-advice.html and style.css

- advice/cvalenciano-advice.html
- css/style.css
- index.html
A little advice that works for me!
> Advice added by Christopher Valenciano

- advice/riacabral-advice.html
- css/style.riacabral-advice.css
- index.html
Hi there,
I updated my URL link in the index.html file, and I updated both CSS and HTML.
Thank you!
-Ria
> Ria experiments

- advice/shanice-advice.html
- css/shanice-advice.css
- index.html
> Added my advice and CSS

- advice/advice-kaseyfahey.html
- css/style.css
- index.html
i changed kasey advice and styling
> fork-edits

- advice/abbey-advice.html
- css/style.css
- index.html
add page for abbey's advice, modify styles and add link to page
> Abbey's advice

- advice/advice-hhoefele.html
- css/style.css
- index.html
Added an advice page for hhoefele to share.
> added an advice page for hhoefeoe

- advice/kimlamberth-advice.html
- css/Kim-l-advice.css
- index.html
> Kim's advice added

- advice/melaniejansen-advice.html
- css/melaniejansen-advice.css
Finally submitting my changes for this challenge!
> updates from melanie

- advice/amandaluu-advice.html
- css/style.css
- index.html
> Added Amanda's Advice

- advice/laurentogie-advice.html
- css/style.css
- index.html
> adding my advice post, link to index, and css for post

- advice/ashleymacq-advice.html
- css/ashleymacq-style.css
- index.html
> added advice page, added link to index

- andyhall-advice.html
- css/andyhall.css
- css/style.css
Some advice I would have loved to have when starting to learn to code!
> added advice and styled

- advice/amandaluu-advice.html
- css/amandaluu-advice.css
> adding amanda luu advice (again)

- advice/vyallup-advice.html
- css/vyallup-style.css
- index.html
> add advice page with custom css and link to index

- advice/clarelewis-advice.html
- css/clarelewis-advice.css
- index.html
> Clare advice

- advice/mreyesadvice-template.html
- css/mreyes-style.css
- index.html
> edited index advice and css files

- advice/advice-carrol.html
- css/carrol-style.css
> add advice-carrol.html and carrol-style.css

- advice/carolineSmith-advice.html
> carolinesAdvice edits

- advice/advice-marina-snyder.html
- css/style.css
Added a new advice page and style for that page. Nothing fancy, just getting the hang of GitHub.
> Experiments

- advice/erocks-advice.html
- css/style.css
- index.html
Some advice that I would like to share with the group!
> Erika added advice!

- advice/alena-advice.html
- css/alena-style.css
- index.html
> added my own advice

- advice/desinessa-advice.html
- css/desinessa-style.css
> desinessa's advice added

- advice/amyj-advice.html
- css/amyj-style.css
Hi there, 
I'd like to add my advice to the mix!
Thanks, 
Amy
> Added amyj-advice.html and amyj-style.css

- advice/advice-putaylor315.html
- css/style.css
I'm somewhat winging it here, but I think it's slowly coming together.
> Beth added advice. 

- advice/vorce-advice.html
- css/vorce-advice.css
- index.html
> changes fork

- advice/frances-advice.html
I added some advice I'd love to share! :)
> added frances' advice

- advice/miramarshall-advice.html
A little advice I'd like to share.
> Adding Mira's advice to page

- advice/mariahiggins-advice.html
- css/mariahiggins-advice.css
Advice from a newbie to newbies...
> add Maria Higgins advice

- advice/advice-caraslavens.html
- css/style.css
- index.html
A little behind on this assignment!
> added my advice & style

- advice/evey-advice.html
- css/style.css
- index.html
> Evey's advice practice

- advice/twobit-advice.html
- css/twobit-advice.css
- index.html
> Added TwoBitSpecialist's Advice

- advice/mmh-advice.html
- css/mmh-style.css
- index.html
Hi! I've added and styled my advice as part of the Skillcrush 105 class.
> added and styled my advice

- css/style.css
> Janessa style edits

- advice/advice-ddp.html
- css/style.css
- index.html
dayispatterson & ddp are both my work; repeating Git instruction in wordpress blueprint
> merging ddp-advice

- css/style.css
- index.html
> advice page school

- advice/elris-advice.html
- css/elri.css
- index.html
added my advice plus included a seperate CSS file
> Added Advice :)

- advice/gladysbarroga-advice.html
- css/style.css
- index.html
Added my advice info to index.html, style.css, and new html.
> added new advice page

- advice/advice-sarabouchard.html
- css/sarabouchard-style.css
- index.html
Here is some advice I would like to share.
> Added Sara B's advice

- advice/mamie_advice.html
- css/mamie.css
- css/style.css
- index.html
> Added mamie

- advice/advice-juliestuckey.html
- css/juliestuckey-style.css
- index.html
Here is the advice that I have added!
> I have added my advice for new Skillcrushers

- advice/ilana-advice.html
- css/ilana-style.css
- index.html
> Ilana Updates

- css/style.css
- index.html
> livs advice

- advice/jose-sanchez_advice.html
- css/jose-sanchez-style.css
- index.html
Hi,
I´ve just updated the index.html with my line, add my comments on my page and used a separate css, this is why the main.css remains intact.
> changes from London, UK

- advice/skh-advice.html
- css/skh-style.css
- index.html
Adding my advice for Skillcrushers
> added advice and updated styles

- advice/krystald-advice.html
- css/krystald-advice.css
- index.html
This is a really great exercise, I loved seeing the different pages! Some were so much fun!
> add Krystal D's advice page

- advice/clementine-advice.html
- css/style.css
- index.html
Here we go everyone, some advice for you!
> Clementine gives you some advice!

- advice/jabulile-advice.html
- css/jabulile.css
made changes to html and css files
> made changes to html and css file

- advice/cameronwebb-advice.html
- css/style.css
- index.html
> added my advice page, altered my styles, and added a link to it in index

- advice/hoodoolady-advice.html
- css/hoodoolady-style.css
- index.html
I hope this works!   Let me know if I dorked anything up, yo!  :)
> Hoodoo Lady's (Amy) advice

- advice/natalierose-advice.html
- css/natalierose-style.css
- css/style.css
- index.html
> added natalierose advice page, styles and updated index list.

- advice/jesswentworth-advice.html
- css/style.css
- index.html
> Jess Wentworth Advice

- advice/tylarpierson-advice.html
- css/style.css
- index.html
> Tylar Added Advice

- advice/advice-tracy.html
- css/tracy-style.css
- index.html
> Advice from Tracy

- advice/williamperez-advice.html
- css/williamperez.css
- index.html
> added css and new advice file

- advice/mmatos-advice.html
- css/style.css
- index.html
my advice page for Skillcrush 104 homework
> giving my advice

- advice/advice-rachel.html
- css/style.css
- index.html
> Rachel's Advice

- advice/sharvani-advice.html
- css/style.css
- index.html
> fork clone and push

- advice/christinachron-advice.html
- css/christinachron-style.css
- index.html
Advice made from  Christina C.
> changes to html and css files

- advice/corcutt-advice.html
- css/corcutt-style.css
- index.html
> Updated to add advice from Cheryl

- advice/emilynickerson-advice.html
- css/emilynickerson-style.css
- css/style.css
> emilynickerson advice

- advice/christyfennewald-advice.html
Some advice about coding from Christy
> christy advice page

- advice/lona-advice.html
> changed advice

- advice/advice-arina.html
- css/arina-style.css
- css/style.css
- index.html
> My advice branch

- advice/theresas-sage-advice.html
just a quick edit by me, with many, many wise words...
> theresas-sage-advice.html

- advice/lolo-advice.html
- css/lolo-style.css
- index.html
> Git 105 class - Lolo's advice

- advice/valentine-advice.html
- css/style.css
- index.html
My advice page. I was having trouble with my CSS showing up. Not sure what is wrong.
> New advice

- advice/steven-advice.html
- css/style.css
- index.html
> Steve advice

- advice/seancody-advice.html
- css/style-seancody.css
- css/style.css
I added an anchor link to my own advice page, created that advice page, and created some custom styling.
> Sean Cody's Advice

- advice/cindyhoward-advice.html
- css/cindyhoward-advice.css
- index.html
> changed font

- advice/jojosephs-advice.html
- css/jojosephs.css
- index.html
Advice for new developers yay :)
> Advice from Jo

- advice/hiro-advice.html
- index.html
> hiro's addition

- advice/katiegustafson-advice.html
- css/style.css
- index.html
> edited katie advice page, css and html

- advice/monika-advice.html
- css/style.css
- index.html
Some advice I would like to share
> added Monika advice and styled page

- advice/advice-JessicaA.html
- advice/jessicaarcher-advice.html
Some advice I wanted to share.
> Jessica adding advice

- advice/james-advice.html
- css/style.css
- index.html
Added James' advice and included link to his page on index.html
> James added advice

- advice/debmackey-advice.html
- css/debmackey-advice.css
- index.html
I have some awesome changes here! Let me know your thoughts.
> css and advice added link to html

- advice/buennyfry-advice.html
- css/buennyfry-style.css
- index.html
I would like to add my advice into the project.
> 104 branch

- css/style.css
- index.html
Added advice I have gathered from going through SkillCrush.
> Made changes to personal advice page

- advice/janj-advice.html
- css/janj-style.css
- index.html
Advice to share for Skillcrush 105 lesson.
> add JanJ advice

- advice/jennifer-w-advice.html
- css/style.css
- index.html
Some solid advice from Homer Simpson!
> jennifer w update

- advice/sarah-montoro-advice.html
- css/sarah-montoro-styles.css
- css/style.css
> personalized advice text and changed background to grey

- advice/trevs-advice.html
- css/style.css
- index.html
> trevs modified files

- advice/phoebejlau-advice.html
- css/phoebejlau.style.css
- css/style.css
> Phoebe's advice page

- advice/dianapol-advice.html
- css/dianapol-style.css
some advice i would like to share :)
> diana added advice

- advice/hannagerman-advice.html
- css/hannagerman-style.css
- css/style.css
- index.html
Added my own advice page to share
> Hannagerman advice

- advice/advice-annakleb.html
- css/annakleb-style.css
- index.html
Added some small words of advice in addition to a separate css page for my advice page.
> Added my own css page and advice

- advice/hdoucet-advice.html
- css/hdoucet-styles.css
- index.html
> Adding Heather's advice

- advice/jaime-advice.html
- css/jaime-style.css
- index.html
> added jaime's advice

- advice/richards-advice.html
- css/richards-advice.css
- index.html
A little advice, not very original, but the best I could think of at the moment.
> Added Richard's Advice

- advice/antonella-advice.html
- css/antonella-advice.css
- index.html
Add Antonella's advice files. Clean up spaces in index list.
> Antonella advice

- advice/rachelstevens-advice-104.html
- css/rachelstevens-style.css
- index.html
My advice to newbie coders html text edits and styling.
> added styles to my advice html page

- advice/relative-dens-advice.html
- css/relative-dens-style.css
- index.html
New advice page added, including separate css style doc.
> Added new html page & css for relative-density.

- advice/sharon-advice.html
- css/style.sharon-advice.css
- index.html
> added sharon-advice

- advice/advice-hollygualco.html
- css/hollygualco-advice.css
- index.html
"added holly gualco advice html and css"
> added holly gualco advice html and css

- advice/alanaaxley-advice.html
- css/alana-advice.css
- index.html
I'm here, I'm queer, and I've brought some advice!
>  adding myself to the advice collumn

- advice/kaylajoy-advice.html
- css/kaylajoystyle.css
- index.html
> added kayla joy's advice

- advice/kitty-p-advice.html
- css/kitty-p-style.css
- index.html
Just wanted to add my 2 cents of advice to the skillcrush git project.
> adding my 2 cents of advice

- advice/rebecca-advice.html
- css/rebecca-style.css
- index.html
> add advice link-html-css

- advice/laurelbeyers-advice.html
- index.html
a little advice i have for other students :)
> Laurel added advice! woot woot!

- advice/madlen-advice.html
- css/madlen-style.css
- index.html
Madlen analyzed submissions to Skillcrush 105 challenge and would like to push to the upstream remote
> Madlen's data analysis of the advice.html submissions

- advice/hmtarz-advice.html
- css/style.css
Some advice I would like to share...!
> hmtarz added advice

- advice/meredithmyers-advice.html
- css/meredithmyers-advice.css
Modified html and css for personal advice
> added meredith advice page

- advice/genaeb-advice.html
- css/genaeb.css
Wow, what a challenge! Hopefully, everything is in order.
> customized personal advice

- advice/victoria-advice.html
> adding victoria-advice

- advice/lcworthy-advice.html
- css/lynn_style.css
- css/style.css
- index.html
> First commit to Skillcrush 104

- advice/tsouhrada-advice.html
New advice from skillcrush 105 - git git hub and the command line lesson
> tsouhrada advice added

- advice/eliseburton-advice.html
- css/eliseburton-style.css
Adding my advice and a gif for good measure.
> html and css changes

- advice/advice-nickc.html
- css/nickcstyle.css
> Created new advice page

- advice/carolineseigel-advice.html
Some advice that I edited (^_^)
> A few changes to colors, text alignment and content

- advice/advice-anthonyiasiello.html
- css/style.css
- index.html
Hey i just added my advice page with some css in the style.css file
Let me know what you think
Antid0te
> Added anthony iasiellos advice page

- advice/jeremy-mwangelwa-advice.html
- css/style.css
- index.html
I added some advice. He/she who has an ear, let him/her hear what the Spirit has to say.
> Jeremy added advice

- advice/tara-advice.html
> minor style changes

- advice/monicaroy-advice.html
- css/style.css
> Firstbranch

- advice/julie-advice.html
- css/julie-style.css
I added a little advice and made some changes to text and background color on my advice page.
> changes to text and background color

- advice/adrianmartinez-advice.html
- css/adrianmartinez-advice.css
- index.html
> adrian martinez's advice

- advice/advice-suzis.html
- css/style.css
- index.html
Here is the advice I would like to share.
> added suzi's advice page

- advice/sue-tang-advice.html
- css/sue-tang-advice.css
- index.html
Advice Sue Tang wants to share
> sue tang advice

- advice/ashleys-advice.html
- css/style.css
- index.html
Added Ashley's Advice link to index.html. Links to ashleys-advice.html. 
Styled with style.css under Ashley Rudy's Style comment.
> Added Ashley's Advice Page with CSS styles added to top of style.css

- advice/angelafoster-advice.html
- css/style.css
I have updated changes made to master html and css stylesheet code sheets.
> Made additional changes to html code and css stylesheet

- advice/debbyermel-advice.html
- css/debbyermel-style.css
New advice file, that I would like to add.
> Debora Ermel Advice file added

- advice/anthony-advice.html
- css/anthonyharvey-style.css
- index.html
Added some advice that I would give to myself at the beginning of my coding journey.
> added my advice and style changes

- advice/sophie-ro-advice.html
- css/sophie-ro.css
- index.html
Just adding my little bit of advice to the code
> sophie's words of wisdom

- advice/laurentia-advice.html
- css/laurentia.css
- index.html
More like my internal motivation
> Laurentia's advice added

- advice/sevebaudrand-advice.html
- css/sevebaudrand-advice.css
- index.html
> styled my seve's advice page

- advice/carey-advice.html
- css/carey-style.css
- index.html
My advice to be added to the page.
> Carey's updates to advice html/css

- advice/artistwhocodes-advice.html
- css/artistwhocodes-style.css
I added an advice and kept Skillcrush's advice as well.^^
> Pamelabranch

- advice/andym-advice.html
- css/andym-advice.css
- index.html
Andy's supplementary advice and style changes
> Andy M advice

- advice/kelsea-advice.html
- css/kelsea-advice.css
- index.html
Some advice I would like to share
> added kelsea's advice

- advice/crystelcabrera-advice.html
- css/crystel-style.css
- index.html
> added crystels advice file

- advice/manjula-advice.html
- css/manjula-advice.css
i have added html and css , check out it
> manjul-advice html and css file created

- advice/lukemiller-advice.html
- css/lmiller-style.css
- index.html
Some advice I would love to share.
> Luke added advice

- advice/advice-martin-slack.html
- css/martin-style.css
- index.html
> Martin's Advice page

- advice/greenwarrior-advice.html
- css/greenwarrior-style.css
- css/style.css
- index.html
Same advice with different layout added.
> Greenwarrior added an advice page

- advice/santiarivera-advice.html
- css/santiarivera-style.css
- index.html
Added some advice I would like to share.
> Added my advice to the folder

- advice/yanessa-advice.html
- css/yanessa-styles.css
- index.html
> added yanessa-advice

- advice/advice-charlotte.html
- index.html
Advice that I would love to share.
> added advice html and link

- advice/advice-haley.html
- css/haley-style.css
git commit -m'updates to haleys advice
> updates to haley advice

- advice/alessionovi-advice.html
- css/style.css
> cambiato stile e fatto mia pagina

- advice/dandretolbert-advice.html
- css/dandre-style.css
> Added a dandretolbert.html and dandre-style.css files

- index.html
> Zoe added advice

- advice/johnnicholson-advice.html
- css/johnnicholson-style.css
Some things I learned long ago, and have applied to learning code.
> V2.0 John added advice

- advice/advice-lexiemiller.html
> Added Advice

- advice/kayfo-advice.html
> added kayfo advice

- advice/cynthiagibson-advice.html
- css/cynthiagibson-advice.css
- index.html
> index modified, 2 cynthiagibson-advice files added

- advice/advice-nikkiheyman.html
- css/style.css
- index.html
Some advice that I would like to share.
> Nikki's advice

- advice/aliciagoolsby-advice.html
- css/aliciagoolsby-style.css
- index.html
Hoping you will be able to see my advice for newbies!
> added message and styling for advice for newbies

- advice/suellenc-advice.html
- css/suellenc-advice.css
- index.html
Changed content. Added my advice and styling.
> suellenc advice

- advice/cbonvicin-advice.html
> cbon advice added

- advice/mysteve-advice.html
- css/steves-style.css
> Here's some advice

- advice/sherryc-advice.html
- css/sherryc-style.css
submitting a pull request exercise
> making a change to skillcrush-104 repo-sherryc

- advice/advice-vanderwoo.html
- css/vanderwoo.css
- index.html
> made my advice page

- advice/yoona-advice.html
- css/yoona-advice.css
- index.html
Contributed a bit of my own advice, thanks.
> Edit and customize my advice page

- advice/advice-mona.html
- css/mona-style.css
- index.html
updated to add my advice - new advice page, new advice css, link to new page at bottom of index.html
> friday lesson stuff - advice files added for me specifically.

- advice/sarag-advice.html
- css/sarag-style.css
- index.html
> Sara's Advice

- advice/dawson-advice.html
- css/dawson-style.css
- index.html
Created own advice file "dawson-advice.html" in advice folder.
Created own style sheet "dawson-style.css" in css folder.
Added link to index.html - "dawson-advice.html".
> Dawson's Advice

- advice/stephschre-advice.html
- css/style.css
> new advice and style files

- advice/advice-jaimee.html
- index.html
> first changes

- advice/advice-ngaire.html
- css/ngaire-style.css
- index.html
Added a new .css and new index.html. Updated main index.html
> created files for ngaire

- advice/vickigreer-advice.html
- css/vickigreer-style.css
Some advice I'd love to share, from Skillcrush 105.
> Updated previous advice

- advice/drpepper-advice.html
- index.html
Advice from Alex! (I had some Dr. Pepper) :+1:
> dr pepper advice

- advice/erinjohnson-advice.html
- css/style.css
- index.html
Yikes! I added some advice and left the rest. My theory: Don't reinvent the wheel!
> my first clone and fork

- advice/leacamara-advice.html
- css/style.css
- index.html
Added some advice to our collection!
> Lea's advice

- advice/sarahz-advice.html
- css/style.css
- index.html
> Sarah advice commit

- advice/juliakenny-advice.html
- css/juliakenny-style.css
- index.html
> julia-kenny-advice

- advice/advice-sinacio.html
- css/serge-style.css
- index.html
I think you gonna like it 👍 :)
> Serge added an advice.

- advice/kengreen-advice.html
- css/kengreen-style.css
- index.html
added some advice the I was asked to share
> added advice from Ken Green

- advice/katr-advice.html
This is my advice to newbies 👍
> added kat advice

- advice/sarah-d-advice.html
- css/sarah-d-advice.css
Added sarah-d-advice.html and sarah-d-advice.css files
> sarah-d-changes

- advice/rhondaful-advice.html
Some advice for Newbies that I think is helpful.
> updated advice and file links

- advice/alexh-advice.html
I'm learning to work with other developers!
> personalized

- advice/debra-advice.html
- css/style.css
Good God I hope this worked! Added my advice.
> Debra's Advice (my105)

- advice/jessica-m-advice.html
- css/style-jessica-m.css
Please review my additions and add to the advice list 
Thank you,
Jessica
> Jessica M's Advice

- advice/kelseyfecho-advice.html
- css/kelseyfecho-style.css
> added my advice and style pages

- advice/donny-advice.html
- css/donny-style.css
I thought I could spruce things up a bit :)
> Made new Donny html and css files

- advice/géraldine-advice.html
- css/geri-style.css
Here are some awesome changes that I would love to share:)
> Awesome changes yay!!!

- advice/tessa-advice.html
- css/style.css
- index.html
> Tessas Advice

- advice/advice-nya.html
> Nya's simple advice

- advice/advice-djstillio.html
- css/djstillio-style.css
- index.html
> added dakota's advice

- advice/ashleyhabgood-advice.html
- css/style.css
Practice creating a pull request.
> adding ashley h. style

- advice/sarahcyradvice.html
- css/style.css
- index.html
Advice I would love to share. It allowed for self-reflection for me as well :)
> added-sarah-cyr-advice

- advice/advice-naseem.html
- css/style.css
- index.html
> naseem's advice commit

- advice/lhendricks-advice.html
- css/lohendricks-style.css
- css/style.css
- index.html
- ruby/lhendricks.rb
Adding file to forked repository for ruby class
> Adding file to forked repository

- css/style.css
- index.html
> jvillars advice

- advice/advice-megan-deme.html
- css/megand-style.css
- css/style.css
- index.html
Just some advise I'd like to share
> Megan Advise Added

- advice/puja-advice.html
- css/puja-advice.css
- index.html
Added some advice I would like to share.
> added puja-advice

- advice/rikkigoss-advice.html
- index.html
Here is a little advice that I have!
> Rikki's Advice added

- advice/andream-advice.html
- css/style.css
Hello! I have completed my advice page. Please review! Give feedback if needed or pull that bad boy if you feel its ready!
Thank you for your time!
Andrea
> Andream advice html & css update

- advice/taqwarushdan-advice.html
- css/taqwa-styles.css
- index.html
> Taqwa added advice

- advice/advice-laura.html
- css/style-laura.css
- index.html
> Added Laura's Advice page and new CSS stylesheet

- advice/marieorriss-advice.html
- css/marieorriss-style.css
- index.html
> Marie added her advice

- advice/annafoldvari-advice.html
- css/styleaf.css
- index.html
Hello,
here is my advice.
Anna
> Added Anna F's advice

- advice/alexandraalex-advice.html
- css/style.css
- index.html
Important to share the importance of caffein. :)
> Alexandra added some advice

- advice/rheamarie-advice.html
- advice/rheamarie2-advice.html
- css/style.css
- index.html
- ruby/rhea.rb
> Rheamarie practice

- advice/advice-juliette.html
- css/style.css
- index.html
> Juliette added an advice page

- advice/liz-e-advice.html
- css/style.css
- index.html
some advice that I would love to share
> liz's advice

- advice/erika-advice.html
- css/style.css
- index.html
Advice that I would like to share :)
> Erika's Added Advice

- advice/laurie-advice.html
- css/laurie-style.css
- index.html
> Added Laurie's Advice html and css

- advice/chad-advice.html
- css/chadRicard-style.css
- index.html
Hi,
I updated the page with a new html entry. Let me know if this works out.
Thanks
> added chad-advice page. Updated minor html syntax errors

- advice/tiffanykantz-advice.html
- css/style.css
- index.html
A few bits of advice that I consider helpful.
> Added and styled my advice page

- advice/clairekirby-advice.html
- css/style.css
Some great quotes I would love to share with everyone!
> added clairekirby-advice.html and additions to style.css file

- advice/ally-advice.html
- css/style.css
- index.html
Added link to index.html and added ally-advice.html
> advice changes

- advice/jazz-advice
- css/style.css
- index.html
> jazz advice

- advice/tootechtrav-advice.html
- css/style.css
- index.html
Leaving some advice for the youngins ;b
> tootechtrav advice

- css/style.css
- index.html
This was a fun and challenging assingment
> added lenny advice

- advice/amandaworthington-advice.html
- css/style.css
- index.html
> amanda worthington advice addition and update

- advice/advice-katier.html
- css/katier-style.css
- index.html
> adding katier files

- advice/kerri-advice.html
- css/style.css
- index.html
Some advice I would love to share!
> added Kerri's advice

- advice/danidewaal-advice.html
- css/style.css
- index.html
Some coding advice I'd like to add.
> added Dani's advice page

- advice/evanj-advice.html
- css/style.css
- index.html
Some advice that I would love to share!
> My contribution to the Skillcrush 104 advice project

- advice/cpastorick-advice.html
- css/style.css
Some advice that I would love to share!
> changed css styles and updated html

- advice/lindsay-advice.html
- css/style.css
commented out for the sake of experiments
> commented out some styles

- advice/jenettore-advice.html
- css/style.css
- index.html
Some advice that I would love to share!
> Made changes to my advice files

- advice/smartsuzyadvice.html
- css/style.css
- index.html
This is going to take a lot of practice
> added styles for smartsuzy

- advice/linzfrank-advice.html
- css/style.css
- index.html
> linzfrank's advice

- advice/manuelramos-template.html
- css/manuelramos-advice.css
- index.html
hi there. just doing my exercises :)
> link added

- advice/advice-gab.html
- css/style.css
- index.html
Going through 105 as one of my personal OKRs! This is a great review and refresher. love you skillcrushers reviewing my code! xoxo
> adding in gab's advice

- advice/beckyt-advice.html
- css/beckyt-style.css
- css/style.css
- index.html
Advice because sharing is caring
> Becky T's words of wisdom

- advice/advice-kristin.html
- css/style.css
- index.html
Adding advice-kristin to html and css.
> added an html for kristin, updated index and css

- advice/advice-charissa.html
- css/charissa-advice.css
- index.html
> charissa advice

- advice/leticia-advice.html
- css/style.css
- index.html
> New advice page by Leticia

- advice/sandra-advice.html
- css/style.css
- index.html
> sandra's advice

- advice/racheldicesare-advice.html
- css/style.css
- index.html
> Rachel advice

- advice/jessicapowell-advice.html
- css/jessicapowell-style.css
- index.html
Just wanted to check out the pull request function. :)
> Jessie's Six Tips for Productivity

- advice/anwegner-advice.html
- css/style.css
- index.html
Amanda added & styled her advice page.
> text & style for anwegner advice page

- advice/kims-advice.html
- css/kims-style.css
- index.html
Hopefully, it'll help someone.
> Kim added her advice

- advice/briannaa-advice.html
- css/briannaa-style.css
- index.html
> Brianna's Advice and Styles

- advice/nathalia-bailey-advice.html
- css/style.css
- index.html
Added some pink & more contrast to the headers & paragraphs here!
> nathalia's commits

- advice/justcallmekat-advice.html
- css/kitkat-advice.css
- index.html
Submitting a pull request to complete the 'Submit a Pull Request' 105 lesson.
> SkillCrush 105: Submit a Pull Request

- advice/zoe-advice.html
- css/zoestyle.css
- index.html
Really hope it works this time Sharon :)
> Zoe's Advice

- advice/maureenomahony-advice.html
- css/maureenomahony-style.css
- index.html
styled up my very own advice page!
> created my own advice page

- advice/caseymorris-advice.html
- css/style.css
- index.html
Here are a couple tips I would love to pass on :)
> added Casey's Advice page

- advice/miranda-advice.html
- css/miranda-advice.css
- index.html
> Adding Miranda's Advice

- advice/candicehendrick-advice.html
- css/candice-style.css
- index.html
> added candice's advice to website

- advice/andra-advice.html
- css/style.css
- index.html
> Andra advice

- advice/olesiabaginski-advice.html
- css/style.css
- index.html
Some advice I'd love to share.
> Olesia added some advice

- advice/kshimrob-advice.html
- css/ksr-advice.css
- index.html
> krob added

- advice/loganturner-advice.html
- css/style.css
- index.html
Updated style.css, index.html with link to new advice page.
> Logan's added advice

- advice/abbia-advice.html
- css/style.css
- index.html
added my advice html file, styled in style.css, cleaned up the style.css file so others' styles weren't overruling everything, added link to my advice in index.html and added some minor styling :)
> added my two sense and tidied up a bit

- advice/kiera-advice.html
- css/style.css
- index.html
Here's my advice that I would like to add.
> Kiera's Advice :)

- advice/sfranz_advice.html
- css/style.css
- index.html
Some newbie advice I want to share. :)
> Stephanie added advice

- advice/krystlescott-gold-advice.html
- css/style.css
- index.html
Suggestions for future coding warriors.
> Krystle's advice added

- advice/angie-advice.html
- css/angie-advice.css
- index.html
> Advice project

- advice/kevin-advice.html
- css/kevin-style.css
- index.html
> Kevin adds advice

- advice/jenn-advice.html
- css/style.css
- index.html
My advice that I'd like to share!
> Added Jennifer Coyle's advice, CSS and updated index.html

- advice/biancas-advice.html
- css/style.css
- index.html
> Bianca added advice!

- advice/laureng-advice.html
- css/laureng-style.css
- index.html
Things I've learned and would love to share!
> Added Lauren's Advice

- advice/krislink-advice.html
- css/krislink-style.css
- index.html
Here is my advice page to share.
> Kris' edits

- advice/jeannes-advice.html
- css/jeannes-advice.css
- index.html
Advice I'd like to share about personal learning/working style.
> Jeanne's Advice 

- advice/AskAlicia-advice.html
- css/style.css
- index.html
Hi,
Here is the HTML and CSS for my advice page.
Thank you for taking a look.
> Experiments page for Ask Alicia

- advice/als-advice.html
- css/style.css
- index.html
> added Al's advice

- advice/breannh-advice.html
- css/style.css
- index.html
> Adding my advice

- advice/jess-e-m-advice.html
- css/jess-e-m-style.css
- index.html
Some learning advice to share with others.
> Jess edits

- advice/zoraida-advice.html
- css/zoraida-style.css
- index.html
Here's my advice for the page :)
> Zoraida Adding Advice

- advice/jrpjrp-advice.html
- css/style.css
- index.html
> my advice and css

- advice/advice-jrecher.html
- css/jrecher-style.css
- index.html
I added my page to the main, created my own css stlye, and an advice page.  Sorry I didn't make if mobile first... but I did end up making it for 400px eventually.
> added jrecher advice

- advice/advice-crystal.html
- css/style.css
- index.html
Made my first pull request in Github! :)
> advice updates

- advice/kimberlys-advice.html
- css/style.css
- index.html
I did this pretty fast, so it's not very complete. My best advice Goggle it!
> kim added advice

- advice/samuelo-advice.html
- css/samuelo-advice.css
- index.html
Hello Skillcrush,
Changes:
samuelo-advice.html was added to the list. 
Thanks to Sharon and Cassie.  :)
> 104 branch 1

- advice/cat-advice.html
- css/cat-style.css
Added cat advice page & css, edited index.html.
> Cat changes

- advice/advice-heatherh.html
- css/style.css
- index.html
> Heather H's advice additions

- advice/advice-jjdwolfe.html
- css/jjwolfe-style.css
- index.html
I created an advice page and made the background color pop!
> I created and styled my personal advice page

- advice/mollyhartwick-advice.html
- css/mollyhartwick-style.css
- index.html
> updated personal advice page including new style file

- advice/advice-katherine.html
> added advice-katherine

- advice/melissabouchard-advice.html
- css/style.css
- index.html
Some advice from a very wise person... :) haha
> Adding Melissa's advice

- advice/ericpatrick-advice.html
- css/ericpatrick-advice.css
- index.html
Some advice that I would love to share.
> Branch one

- advice/aubriestlouis-advice.html
- css/style.css
- index.html
This is my first pull request for the skillcrush 105 class!!! Killin' it!
> Aubrie stlouis

- advice/sylvia-advice.html
- css/sylvia-style.css
- index.html
Added html advice page with css file.
> Advice added

- advice/nataliesaleh-advice.html
- css/nataliesaleh-advice.css
- index.html
> Natalie's advice page added

- advice/gregschmitt-advice.html
- css/style.css
- index.html
> updated style and name

- advice/sarahyu-advice.html
- css/style.css
- index.html
> added sarah's advice

- advice/hector-advice.html
- css/hector-advice.css
- index.html
Some helpful advice and confidence boost to those that need it. It sure helped me, thank you. Created advice/hector-advice.html, created css/hector-advice.css, and added link to index.html.
> Git practice

- advice/hvincent-advice.html
- css/style.css
- index.html
I want everyone to kick impostor syndrome to the curb!
> Heidi Added Some Advice

- advice/janellea-advice.html
- css/janellea-style.css
- index.html
I have added my own advice page along with a style page for it. I have added my page to the list of links on the index.html page. 
Thank you!
> Janelle A's Advice for Newbies

- advice/lauragieg-advice.html
- css/laura-style.css
- index.html
> Personalize

- advice/tiffanyo-advice.html
- css/style.css
- index.html
> Tiffany added Advice

- advice/advice-mharrison.html
- css/advice-mharrison.css
- index.html
> Adding M. Harrison advice

- advice/carrief-advice-template.html
- css/carrief-advice.css
- index.html
> added carrie specific files and code

- advice/brandon-advice.html
- css/brandon-advice.css
- index.html
> Added My Advice Page w/ CSS

- advice/ronickthomas-advice.html
- css/ronick-style.css
- index.html
> changed classes font styles and sizes

- advice/stacey-advice.html
- css/stacey-style.css
- index.html
> First EVER pull request

- advice/eshton-advice.html
- css/style.css
- index.html
> Eshton's advice

- advice/kayls-advice.html
- css/style-kayls.css
- index.html
> Kay's Advice

- advice/kathykemmis-advice.html
- css/style.css
- index.html
> Kathy Kemmis added advice

- advice/sarahs-advice.html
- css/style.css
- index.html
I'd love some feedback!
Thanks!
> Sarahs Advice

- advice/elizabethv-advice.html
- css/style.css
- index.html
> EV added advise and changed some styles

- advice/brandy-advice.html
- css/brandy-style.css
- index.html
I changed some advice, styled the page differently, and added my link to index.html.
> Add Link to index.html

- advice/tsering-advice.html
- css/style.css
- css/tsering-style.css
- index.html
Is this right? Can't figure out!
> style-sheets

- advice/lam-advice.html
- css/lam-style.css
- index.html
Some advise to share with others.
> Lamversion

- advice/lesleyhogg-advice.html
- css/style.css
- index.html
I created advice/lesleyhogg-advice.html, updated css/style.css to add class .lesleyhogg-advice and stylings, and added the link to my advice page to the main index.html file.
> added advice page for Lesley Hogg and updated style css file

- advice/advice-template-ayoukey.html
- css/ayoukey-advice-styles.css
- index.html
> Anne comparing

- advice/advice-lynettelim.html
- css/lynettelim-style.css
- css/style.css
- index.html
Here we go! Some advice I would love to share.
> lynette lim advice

- advice/jennifercarver-advice.html
- css/jennifercarver_style.css
- index.html
Adding advice from Jennifer Carver.
> updated with personal advice

- advice/advice-vlg.html
- css/style.css
- index.html
added my advice for this session of 105
> Vicki Greer's Advice October 2017

- advice/shannawalsh-advice.html
- css/style-shannawalsh.css
- index.html
just learning to work in GITHUB...almost done
> repo push project

- advice/advice-grace.html
- css/style.css
- index.html
> added my advice section and styles

- advice/kessiahs-advice.html
- css/style-kessiah.css
- index.html
Added a little advice for my fellow aspiring tech wizards!
> added Kessiah's Pep Talk for New Tech Wizards

- advice/anisleysv-advice.html
- css/anisley-style.css
- index.html
The git fetch upstream failed (because of public key). I'm not sure if instead I can request a pull from my brand or if I have to merge my brand to my master and after make the pull request. I made both. Please let me know what is the correct procedure to collaborate.
> Trying to merge from my master

- advice/dugancodes-advice.html
- css/style.css
- index.html
Advice that I would like to share
> Adding Advice to Newbies from Dugancodes

- advice/deborah-advice.html
- css/style.css
- index.html
> Adding Deborah's advice

- advice/eps-advice.html
- css/style.css
- index.html
> added eps advice

- advice/sthvecu-advice.html
- css/style.css
- index.html
Susan aka Vegoia in the advice section
> 104 experiments - added Susan's advice

- advice/advice-danielberryman.html
- css/style.css
- index.html
> my experiments learning github

- advice/emilymartens-advice.html
- css/emilymartens-style.css
- index.html
My advice for tech ladies and anyone struggling with a change.
> Added Em Advice page and styles

- advice/jetset-advice.html
- css/jetset-advice.css
- index.html
I have some pure gold I'd like to offer.
> New Advice from JetSet

- advice/erinnunley-advice.html.html
- css/erinnunley-advice.css
- index.html
> changed advice for Erin Nunley

- advice/advice-michaelsm.html
- advice/michaelsm-advice.html
- css/style.css
- index.html
Hey, 
Just adding these test files from SkillCrush 105 - thanks!
> MichaelSM added test files 

- advice/statz-advice.html
- css/style.css
- index.html
Hello! Hope I'm on the right path!
> statz updates

- advice/advice-kathrenefaith.html
- css/style-kathrenefaith.css
- index.html
> Kathrene Faith added advice!

- advice/advice-emmaf.html
- css/emmaf-style.css
- index.html
Advice and style added to complete task
> Added EmmaF advice and style

- advice/ems-advice.html
- css/ems-style.css
- index.html
> Experiments - Advice

- advice/calebs-advice.html
- css/style.css
- index.html
Added very meaningless advice.
> added Caleb's advice

- advice/sandyreef-advice.html
- css/style.css
- index.html
My advice that I want to share.
> Sandy's advice added

- advice/kevinzhao-advice.html
- css/kevinzhao-style.css
- index.html
> Kevin added advice

- advice/dconway-advice.html
- css/dconway-advice-styles.css
- index.html
Some advice I would like to share...
> Dean added his advice.

- advice/cspn-advice.html
- css/cspn-style.css
- css/style.css
- index.html
> Added cspn adviced and stylesheet

- advice/tals-grow-advice.html
- css/tals-style.css
- index.html
> Experiment 3

- advice/advice-bethh.html
- css/style.css
- index.html
> added advice from bethh

- advice/advice-kori.html
- css/kori-advice.css
- index.html
> kori's advice

- advice/bridgetam-advice.html
- css/bridgetam-style.css
- index.html
> bridgets edits

- advice/abi-advice.html
- css/abi-advice.css
- index.html
> Adds for Abi's Advice

- advice/advice-maybemaile.html
- css/style.css
- index.html
Made some changes to the font and color.
> added maile advice

- advice/hoyt-advice.html
- css/hoyt-style.css
- index.html
Added advice page as instructed.
> Added 'Hoyt's Advice' page

- advice/advice-Mai.html
- css/mai-style.css
- index.html
Some advice i would like to share.
> Mai's advice

- advice/nicolerf-advice.html
- css/style.css
- index.html
Nicolerf's advice - git pull request practice
> Gitpractice

- advice/joys-advice.html
- css/style.css
- index.html
A little movie-based advice I would love to share :)
> Joy added advice 

- advice/chrisw-advice.html
- css/chrisw-style.css
- index.html
> Chris W Advice

- advice/loripopo-advice.html
- css/style.css
- index.html
Lori added some of her advice 👍
> added Lori P's advice

- advice/carlosengo-advice.html
- css/carlossengo-advice.css
- index.html
> carlos advice

- advice/jaffacake-advice.html
- css/jaffacake-style.css
- index.html
Created new advice page for skillcrush 105 project. Please let me know what you think.
> Advice needed for html and css codes

- advice/robopingvin-advice.html
- css/style.css
- index.html
> robopingvin added advices

- advice/kiaramartin-advice.html
- css/kiaramartin-advice.css
- index.html
Just a little advice I would like to share. :)
> Kiara added advice 

- advice/emily-v-advice.html
- css/emily-v-style.css
- index.html
> emily-v-advice

- advice/shelbymuntis-advice.html
- css/style.css
- index.html
Some advice I would like to add
> Advice by Shelby Muntis

- advice/lsavoie-advice.html
- css/lsavoie-advice.css
- index.html
My advice to people new to coding.
> Lisa's advice

- advice/marianafreitas-advice.html
- css/marianaf.css
- index.html
> Creating Mariana's Advice

- advice/jamie-mccarville-advice.html
- css/jamie.css
- index.html
New page with a nugget of advice!
> made a new advice page and linked to it from the original page

- advice/terrywarren-advice.html
- css/tdw-style.css
- index.html
> Terry W. Advice

- advice/mac-advice.html
- css/mac.css
- index.html
I had issues with uploading my advice branch after my last pull request, so I went ahead and redid the challenge.
> created advice for new developers

- advice/rachels-advice-template.html
- css/rachelk-advice.css
- index.html
> Completed class lesson

- advice/amandaottosen-advice.html
- css/style.css
- index.html
> Advice branch

- advice/advice-megappleby.html
- css/advice-megappleby.css
- index.html
Some advice I would like to share ...
> add my advice

- advice/nancys-advice.html
- css/style.css
- index.html
Hi, not sure if I'm supposed to be doing this, but here's my pull request for my advice.html for Skillcrush 105, part 13 step 5  :)
> Nancys skillcrush 104

- advice/kristens-advice.html
- css/kristens-advice.css
- index.html
Here is my advice page that I would love to share with my fellow Skillcrushers!
> advice page added and styled

- advice/ericlahoda-advice.html
- css/style.css
- index.html
2nd times a charm:) Ready to merge with my advice.
> I'm looking forward to my advice joining the party

- advice/advice-fraas.html
- css/style-fraas.css
- index.html
Some advice that I would love to share.
> Courtney Added Advice

- advice/nancych-advice.html
- css/style.css
- index.html
> added my advice and modified the index file

- advice/aleksab-advice.html
- css/aleksab-style.css
- index.html
> Aleksab's advice-104

- advice/robbsky14-advice.html
- css/robbsky14-advice.css
- index.html
Yo! This is some advice from Robbsky14 on how to rock as a programmer!
> Yo! This is some advice from Robbsky14 on how to rock as a programmer!

- advice/marianamendez-advice.html
- css/marianamendez-style.css
- index.html
> Mariana Mendez edits/additions

- advice/advice-vjym.html
- css/style-vjym.css
- index.html
Just some small pieces of advice
> Veronica's Addition

- advice/samcandanedo-advice.html
- css/style.css
- index.html
Advice that could be added to website
> Sam C added advice

- advice/herbie-advice.html
- css/style.css
- index.html
Some advice that could help folks down the road!
> Carlosherbert

- advice/jml-advice-template.html
- css/style.css
- index.html
> Jeannine added advice

- advice/marlene-advice.html
- css/style.css
- index.html
- marlene-advice.html
What do you think about my advice?
> styled text and background

- advice/patti-advice.html
- css/patti-advice.css
- index.html
> Adding Patti's Advice to Skillcrush 104

- advice/advice-mimi.html
- css/mimi-advice-style.css
- index.html
> Mimi gave some advice

- advice/advice-lori.html
- css/lorivaldez-style.css
- index.html
Some advice I'd like to share!
> Lori's advice

- advice/advice-zil.html
- css/zil-style.css
- index.html
I hope I didn't break anything.
> Zil's advice for newbies

- advice/zachdunlap-advice.html
- css/style.css
- index.html
My advice page to go with the others.
> Adding my advice page to the rest

- advice/valeriebiamonte-advice.html
- css/style-valeriebiamonte.css
- index.html
Helpful advice I would like to share
> Added Valerie Biamonte's advice

- advice/bridgetw-advice.html
- css/bridgetw-style.css
- index.html
Here is the advice I'd like to share with other newbies :-)
> Bridget W's Advice

- advice/advice-bircher.html
- css/sbbircher-style.css
- index.html
> Added advice page from me

- advice/advice-brigitta.html
- css/brigitta-style.css
- index.html
> brigitta version of advice

- advice/meganlbailey-advice.html
- css/meganlbailey-style.css
- index.html
> Experiments104

- advice/tees-advice.html
- css/tees-style.css
- index.html
Some advice to share...but beware it's worth what you pay for it.
> tees_advice

- advice/advice-suesue.html
- css/style.css
- index.html
So I created a branch and titled it "practice" but looking at this pull request it looks like it says "master." I hope I didn't mess with the master code (because I know it's wrong) but if I did I'm not sure how that happened.
> adding my advice to page

- advice/advice-lisakpierce.html
- css/style.css
- index.html
My advice for other newbies to coding.
> lisakpierce advice add

- advice/advice-saraooo.html
- css/saraooo.css
- index.html
> Added SaraOoo advice

- advice/advice-from-lala.html
- css/lala-advice.css
- index.html
> Lala's Advice 

- advice/kimingram.html
- css/style.css
- index.html
> Changes added by Kim Ingram

- advice/clarice-advice.html
- css/clarice-advice-style.css
- index.html
> Clarice added an advice page and css style sheet

- advice/advice-coartneyfreeland.html
- css/style.css
- index.html
Here is some advice I would love to share with others.
> Coartney added some advice

- advice/ebb-advice18.html
- css/lena.css
- index.html
> Lena's advice

- advice/jgordon-advice.html
- css/style.css
- index.html
Some advice I would love to share.
> Jen added advice :)

- advice/tomilynns-advice.html
Some advice I would like to share with you. I hope you enjoy it!
> My first fork clone and push project

- advice/saras-advice.html
- css/style.css
- index.html
Sara S added advice.. something that keeps me going and reminds me why I started
> Sara S advice

- advice/advice-jasonwilson.html
- css/jasonwilson-style.css
- index.html
Creating my first pull request.
> Adding my repo files

- advice/lenafrantz-advice.html
- css/lenafrantz-style.css
- index.html
I added some advice that I would like to share
> lenafrantz advice

- advice/rcubo-advice.html
- css/style.css
- index.html
A couple of pieces of advice I would like to share!
> New advice from Ruben

- advice/wahldick-advice.html
- css/wahldick-advice.css
- index.html
> Kait added advice

- advice/mikaylah-advice.html
- css/style.css
- index.html
> Added MiKayla H's Advice

- advice/teni-advice.html
- css/style.css
- index.html
Added my page of advice through Skillcrush 105!
> added teni's advice and updated html and css

- advice/alysiam-advice.html
- css/alysiamiller-style.css
- index.html
> Alysia advice

- advice/habashiya-advice.html
- css/habashiya-style.css
- index.html
> My first pull request

- advice/rezika-advice.html
- css/style.css
- index.html
> rezika-advice-added

- advice/rachelalyssa-advice.html
- css/rachelalyssa-style.css
- index.html
> adding rachel advice page

- advice/kle-advice.html
- css/kle-style.css
- index.html
> another branch added

- advice/advice-evelyn-groenwold.html
- css/style.css
- index.html
Hello,
I'm looking forward to adding my advice to the list. :)
Thanks!
> New Advice!

- advice/advice-arshia.html
- css/style-arshia.css
- index.html
Personal advice I would love to share with newbie coders.
> Arshia added advice

- advice/rhondaH-advice.html
- css/style.css
- index.html
> Rhonda Hernandez Advice

- advice/sofiakrsmanovic-advice.html
- css/sofiakrsmanovic-style.css
- index.html
Adding Sofia Krsmanovic's index and CSS. Also linked the index page to the main advice index page
> Sofia Krsmanovic Advice Page

- advice/jeffreyww-advice.html
- css/jeffreyww.css
- index.html
My advice to add to the annals.
> Jeffrey advice for 104-git project

- advice/mollie-advice.html
- css/style.css
- index.html
Notes from this tech crash course so far :)
> mollies advice files

- advice/jessicadaniels-advice.html
- css/jessicadaniels-style.css
these are my additions to the advice project for the skillcrush-104 folder.
> Jessica edits 104

- advice/jessicadaniels-advice.html
- css/jessicadaniels-style.css
- index.html
this is update the index.html part
> adding index.html

- advice/amandak-advice.html
- css/style.css
- index.html
Changes made to the h1 and h4.  Also added background color, changed the text to two columns, and updated the footer.
> added some new css style

- advice/advice-jessab.html
- css/style-jessab.css
- index.html
> added new page for Jess Abejar

- advice/cat-whitehouse-says.html
- css/catwhitehouse-says.css
- index.html
> Cat's changes

- advice/jovietrotta-advice.html
- css/style.css
- index.html
> created customized advice page

- advice/rachels-advice.html
- css/style.css
- index.html
> added advice page and changed css

- advice/advice-erika.html
- css/erika.css
- index.html
> Erika's Advice

- advice/advice-terirogers.html
- css/style-terirogers.css
- index.html
> personalized files

- advice/freds-advice.html
- css/style.css
- index.html
> advice edit

- advice/r-singh-advice.html
- css/r-singh-style.css
- index.html
Some advice that I would love to share.
> Rie added advice :)

- advice/jensadvice.html
- css/style.css
- index.html
Some advice I'd like to share :)
> Jen added advice

- advice/Guthrie-Advice.html
- css/guthrie-style.css
- index.html
> CSS & HTML for Guthrie S.

- advice/bryanherbert-advice.html
- css/style.css
- index.html
Some helpful advice from me.  I hope it helps others.
> Bryan advice

- advice/gregory-i-advice.html
- css/gregory-i-style.css
- index.html
> change and push

- advice/gregweaver-advice.html
- css/gregweaver-style.css
- index.html
This is my first pull request! I hope you like the changes! :)
> Added Greg Weaver

- advice/nancys-advice-again.html
- css/style.css
- index.html
> added nancys-advice-again.html, link in index and changes in stylesheet

- advice/saralayman-advicetemplate.html
- css/saralayman.css
- index.html
Hello :) 
Is this correct?
XO Sara
> Githubexperiments

- advice/nataliebakers-advice.html
- css/nataliebakers-advice.css
- index.html
My advice for new software developers
> add my advice page

- advice/mily-advice.html
- css/style.css
- index.html
> mily's advice added

- advice/relandlogan-advice.html
- css/style.css
- index.html
> Reland's Addition to Page

- advice/binguyen-advice.html
- css/binguyen-advice.css
- index.html
Advice to fellow skillcrushers
> binguyen-advice

- advice/mkw-advice.html
- css/style.css
- index.html
Added my advice to the master list
> Actual edits this time

- advice/melissamanousos-advice.html
- css/style.css
- index.html
- ruby/melissa-manousos.rb
> Add Melissa's file

- advice/lukasvezina-advice.html
- css/style.css
- index.html
I added my advice and added line breaks on the index.html between advices that were on the same lines.
> lukas's advice and line break between advices

- advice/advice-jools.html
- css/style.css
- index.html
> 1st commit for Skillcrush-104

- advice/advice-asha.html
- css/asha-style.css
- index.html
> asha's advice

- advice/randis-advice.html
- css/randis-advise.css
- index.html
> changed the advise with my own style

- advice/eileen-advice.html
- css/style.css
- index.html
Second try - from my fork, not the master.
> Adding advice from Eileen

- advice/alishaarnold-advice.html
- css/alishaarnold-advice.css
- index.html
Here is my advice.
Thank you!
Got a message "Can't automatically merge" is that ok?
> Git advice

- advice/denfer-advice.html
- css/style.css
- index.html
> added denfer advice

- advice/advice-lianechan.html
- css/lianechan-advice.css
- index.html
> my advice on learning to code

- advice/ashens-advice.html
- css/ashens-style.css
- index.html
Let me know if I need to make any changes to this or anything else. Thank you!
> added my own advice html page along with my own css

- advice/demarisbeyene-advice.html
- css/style.css
- index.html
adding in the index.html links and completing the original submission
> Personal changes 3

- advice/advice-kfultz.html
- css/style.css
- index.html
> Katherine's advice edits

- advice/advice-rakoczililla.html
- css/rakoczililla.css
- index.html
> Lilla's advice

- advice/benjaminbeckwith-advice.html
- css/style.css
- index.html
Here is some advice I'd like to offer. Thanks!
> created advice page for forked git repo assignment

- advice/melissag-advice.html
- css/melissag-style.css
- index.html
Adding my advice and learning more about Git!
> adding Melissa's advice page

- advice/saracoyan-advice.html
- css/style.css
- index.html
Added my advice file and added css for my page.
> sara coyan advice

- advice/shamiras-advice.html
- css/shamira-style.css
- index.html
Some advice from personal experience I would like to share :)
> Shamira added Advice

- advice/tiffanylarson-advice.html
- css/tiffanylarson-style.css
- index.html
Some advice I would like to share with skillcrush
> Tiffany Larson added her own advice

- advice/claireshane-advice.html
- css/claireshane-style.css
- index.html
> Adding advice from Claire

- advice/lacey-has-advice.html
- css/style.css
- index.html
Hello, 
I hope this is right, that I am supposed to do a pull request for this project? 
Thank you, 
Lacey :)
> First push 104

- advice/lydia-advice.html
- css/lydia-style.css
- index.html
Lydia's advice page, inspired by Picasso.
> advice Lydia

- advice/laurakamark-advice.html
- css/style.css
- index.html
I added advice I would like to share with others
> Laura Added Advice

- advice/briannaroby-advice.html
- css/style-briannaroby.css
- index.html
Some advice that I would like to share!
> Brianna added advice.

- advice/krisfitz_advice.html
- css/krisfitz-advice.css
- index.html
Here is some advice I would like to share
> Krissy added advice

- advice/nadine-advice.html
- css/nadine-style.css
- index.html
> Nadine Added Advice

- advice/advice-carolinap.html
- css/carolinap-style.css
- index.html
Added my advice page and css style sheet and a link to it in index.html
> Caro p advice

- advice/rachelstephens-advice.html
- css/style.css
- index.html
> added rachel stephens advice page

- advice/lyndapetruccelli-advice.html
- css/style.css
- index.html
> added Lynda Petruccelli's advice

- advice/tanishadavey-advice.html
- css/style.css
- index.html
Some advice that I would like to share.
> added tanishadavey's advice

- advice/kairilliet-advice.html
- css/style.css
- index.html
> added Kai Rilliet's advice

- advice/advice-abbagaylefaith.html
- css/abbagayle-style.css
- index.html
adding an addtional html and css as well as a link on the original index.html to Abbagayle's advice.
> add abbagayle's advice

- advice/nocureforcuriousity-advice.html
- css/nocureforcuriousity-style.css
- index.html
No Cure for Curiosity adding personal advice page.
> No Cure for Curiosity adding personal advice page

- advice/clariss-advice.html
- css/style.css
- index.html
> Created and styled Clarissa Advice page

- advice/advice-daniel.html
- css/daniel-style.css
- index.html
> added daniel

- advice/advice-jay.html
- css/jay-advice.css
- index.html
> I added some advice

- advice/advice-weber.html
- css/style.css
- index.html
hmmmm not sure if I've done this twice now?
> weber's advice

- README.md
- advice/ka1-advice.html
- css/ka1-style.css
- index.html
Hi,
Please discard previous pull. This one is kosher :)
As much comment, correction, suggestion, criticism, etc as you can send.
Thanks.
Regards,
Kweku.
> Kweku's advice html, css and modified index

- advice/advice-savannahbarlow.html
- css/savannahbarlow-style.css
- index.html
Hi. I added some advice and gave it some css. :)
> Added Savannah Barlow Advice HTML and CSS

- advice/maria-wright-advice.html
- css/style.css
- index.html
> added Maria Wright's advice

- advice/philm-advice.html
- css/style.css
- index.html
(and make Weber's style local instead of global) added link to philm-advice.html to index.html.
> Add philm-advice.html, changed style.css to include my style 

- advice/mattpahuta-advice.html
- css/mattpahuta-styles.css
- index.html
Updated index.html and added new advice.html and .css files for 105 exercise.
> 104testbranch new

- advice/tanya-cheek-advice.html
- css/style.css
- css/tanyacheek.css
- index.html
> tanya cheek advice

- advice/michelebrown-advice.html
- css/michelebrown-style.css
- index.html
Some advice for anyone persuing tech.
> Michele's nuggets of wisdom

- advice/advice-kayla.html
- css/style.css
- index.html
I added my own page of advice!
> added Kayla's advice to site

- advice/megans-advice.html
- css/style.css
- index.html
I kept the CSS changes somewhat minimal. I hope that's okay for this exercise.
> created megans advice html and edited style.css

- advice/kellyburgess-advice.html
- css/style.css
- index.html
> Kellyburgess

- advice/clarkcodes-advice.html
- css/clarkcodes-style.css
- index.html
> added clark's advice page

- advice/advice-richroks.html
- css/style.css
- index.html
I left some advice to share.  :)
> added richs advice

- advice/barbara-advice.html
- css/barbara-style.css
- index.html
> Barbara's Advice

- advice/lauren-bench-has-advice.html
- css/style.css
- index.html
I'd like to add my advice to the pile!
> Adding Lauren's advice page

- advice/elena-advice.html
- css/style.css
- index.html
Giving this another try!  Adding my advice and including my styles in 'style.css' and my link in 'index.html'.
> Elena Added Advice

- advice/elizabethhogue-advice.html
- css/style.css
- index.html
I have added an advice page and a link to that page in the main index.html file.
> Added advice page and link

- advice/sweetspot-advise.html
- css/style.css
- index.html
> Added Kris' advice

- advice/lizj-advice.html
- css/style.css
- index.html
Integrated comments specific to Liz J.
> Added liz j advice to page

- advice/katesimone-advice.html
- css/style.css
- index.html
Advice! Would love any feedback. :)
> Updated and styled my page

- advice/nilma's-advice.html
- css/nilma-style.css
- index.html
I'm having fun doing all these practices.
> Nilma Advice practice

- advice/vickihoffmann-advice.html
- css/vicki-hoffmann-style.css
- index.html
> Here are the two new files as well as the modified index

- advice/advice-from-alex-gray.html
- css/style.css
- index.html
Hey, I added in my own advice page!
> added in my own advice page

- advice/advice-libi.html
- css/libi-style.css
- index.html
I created a new advice file and a new style.css to go with it
> Libi advice and style

- advice/kcm-advice.html
- css/kcm-advice.css
- index.html
updated the index file with my link to the new advice html and css file.
> Katie added advice, new css and updated index.html

- advice/marypk-advice.html
- css/style.css
- index.html
> adding Mary's advice

- advice/advice-teriw.html
- css/style.css
- index.html
I made corrections to merge conflict on advice page.  Can you please check?
> skillcrush-104-c

- advice/wuerdeman-advice.html
- css/wuerdeman-style.css
- index.html
Hey I went ahead and did the 104 class project over again since the first time was super confusing for me.  Here are my changes.  Thanks!
> Changes is 104 class project

- advice/advice-kellylayburn.html
- css/kellylayburn-style.css
- index.html
> Kellysbranch

- advice/leah-advice.html
- css/style-leah.css
- index.html
> added leah advice

- advice/advice-margot.html
- css/style-margot.css
- index.html
Create new HTML & CSS files to add Margot's advice in index.
> Add Margot's advice

- advice/Confused212-advice.html
- css/confused-style.css
- index.html
some advice I would love to share.
> added my advice and a few styling pointers

- advice/sjnelson-advice.html
- css/sjnelson-advice.css
- index.html
Any advice would be great!  Not sure what the " Can't automatically merge" message means...is this there all the time or did I do something wrong...thanks in advance.
-Sean
> Added new link to index.html

- advice/mari-advice.html
- css/mari-advice.css
- index.html
> added Mari's advice

- advice/advice-template-andrea.html
- css/andrea-style.css
- index.html
> added-anrea's-advice

- advice/laurajs-advice.html
- css/style.css
- index.html
> added laurajs advice page

- advice/kevinconvery-advice.html
- css/style.css
- index.html
> added personal advice page

- advice/larissa-advice.html
- css/style.css
- index.html
> Larissa's Advice Project

- advice/amypennybacker-advice.html
- css/style.css
- index.html
testing how to fork, clone, and make changes
> Amy's advice

- advice/netanya-advice.html
- css/netanya-style.css
- index.html
> adding Netanya's advice

- advice/advice-tamaragoldson.html
- css/style.css
- index.html
Some advice that I would love to share
> added an advice file and changed style
